apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    app: mongodb
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
  ensure-users.sh: |
    echo "bau #####################################"
    mongo -u admin -p password << EOF
    use videos
    db.createUser( { user: "admin", pwd: "password",roles: [ "readWrite", "dbAdmin" ] } )
    use mp3s
    db.createUser( { user: "admin", pwd: "password",roles: [ "readWrite", "dbAdmin" ] } )
    EOF
