apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rabbitmq
  namespace: remus
  labels:
    app: rabbitmq
spec:
  host: rabbitmq-remus.apps.ocp.mylab.test
  port:
    targetPort: http
  to:
    kind: Service
    name: rabbitmq
    weight: 100
  wildcardPolicy: None
