apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: converter
  labels:
    app: converter
spec:
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi9/python-39:latest
  output:
    to:
      kind: "ImageStreamTag"
      name: "converter:latest"
  source:
    git: 
      uri: "https://github.com/rbuzatu90/ocp-python.git"
      ref: "main"
    contextDir: "microservices/converter" 
#    dockerfile: "FROM openshift/ruby-22-centos7\nUSER example" 
  replicas: 1
  selector:
    app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: image-registry.openshift-image-registry.svc:5000/remus/converter
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
  triggers:
  - generic:
      secretReference:
        name: webhook
    type: generic

