apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: image-registry.openshift-image-registry.svc:5000/remus/converter
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - converter
      from:
        kind: ImageStreamTag
        name: converter:latest
    type: ImageChange
  strategy:
    type: Rolling
